version: "3"

services:
  db-asset-registry:
    image: 'postgres:13.1-alpine'
    container_name: db-asset-registry
    environment:
      - POSTGRES_DB=asset_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  spring-microservice:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    ports:
      - '8080:8080'
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"
      - OTEL_RESOURCE_ATTRIBUTES=service.name=spring-microservice
      - SPRING_PROFILES_ACTIVE=DOCKER
      - JDK_JAVA_OPTIONS=--add-opens=java.base/java.lang=ALL-UNNAMED