--liquibase formatted sql
--changeset kaique.lucena:001
CREATE TABLE public."participant" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "document" varchar(255) NOT NULL,
    "agency" varchar(32) NOT NULL,
    "account" numeric(32) NOT NULL,
    CONSTRAINT "pkParticipant" PRIMARY KEY ("id"),
    CONSTRAINT "ukParticipant" UNIQUE ("document")
);

CREATE TABLE public."registry" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "idPayer" int4 NOT NULL,
    "idReceiver" int4 NOT NULL,
    "value" numeric(21, 2) NOT NULL,
    "dueDate" timestamp NOT NULL,
    CONSTRAINT "pkRegistry" PRIMARY KEY ("id"),
    CONSTRAINT "fkPayer"
            FOREIGN KEY ("idPayer")
            REFERENCES public."participant"("id"),
    CONSTRAINT "fkReceiver"
            FOREIGN KEY ("idReceiver")
            REFERENCES public."participant"("id")
);