--liquibase formatted sql
--changeset kaique.lucena:001
CREATE TABLE public."participant" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "document" varchar(255) NOT NULL,
    "agency" varchar(32) NOT NULL,
    "account" varchar(32) NOT NULL,
    CONSTRAINT "pkParticipant" PRIMARY KEY ("id"),
    CONSTRAINT "ukParticipant" UNIQUE ("document")
);

CREATE TABLE public."registry" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "idPayer" int4 NOT NULL,
    "idReceiver" int4 NOT NULL,
    "value" numeric(21, 2) NOT NULL,
    "dueDate" timestamp NOT NULL,
    CONSTRAINT "pkRegistry" PRIMARY KEY ("id"),
    CONSTRAINT "fkPayer"
            FOREIGN KEY ("idPayer")
            REFERENCES public."participant"("id"),
    CONSTRAINT "fkReceiver"
            FOREIGN KEY ("idReceiver")
            REFERENCES public."participant"("id")
);

--changeset kaique.lucena:002
CREATE TABLE public."status" (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(100) NOT NULL,
    CONSTRAINT "pkStatus" PRIMARY KEY ("id")
);

INSERT INTO public."status" (description) VALUES
    ('NOT_PAID'),
    ('PAID'),
    ('PAYMENT_IN_PROGRESS'),
    ('PAYMENT_ERROR');

ALTER TABLE public."registry"
    ADD COLUMN "idStatus" int4 NOT NULL,
    ADD CONSTRAINT "fkStatus"
        FOREIGN KEY ("idStatus")
        REFERENCES public."status"("id");

--changeset kaique.lucena:003
ALTER TABLE public."participant"
    ADD COLUMN "paymentId" int4;

